name: Build and push back-end server Docker image

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-server

jobs:
  server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install Typescript
      run: npm install -g typescript
      working-directory: server

    - name: Install dependencies
      run: npm install
      working-directory: server

    - name: Log in to container registry
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8 # v3.0.0
      with:
        context: "{{ defaultContext }}:server"
        push: false
        tags: ${{ env.IMAGE_NAME }}

    - name: Release container image
      run: npx semantic-release
      working-directory: server
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
